<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WorldClockWidget</RootNamespace>
    <AssemblyName>WorldClockWidget</AssemblyName>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
    <EmbeddedResource Include="Assets\Cities.json" />
  </ItemGroup>

</Project>
